# Generated by Django 4.2.7 on 2025-06-30 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leavebalance",
            options={
                "ordering": [
                    "employee__first_name",
                    "employee__last_name",
                    "leave_type__name",
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="leavetype",
            options={"ordering": ["name"]},
        ),
    ]
