# Generated by Django 4.2.7 on 2025-06-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0002_alter_leavebalance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="hr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="team_lead_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
