# Generated by Django 4.2.7 on 2025-06-28 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LeaveRequest",
        ),
        migrations.DeleteModel(
            name="LeaveType",
        ),
    ]
