# Generated by Django 4.2.7 on 2025-06-30 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departments", "0003_alter_department_options_department_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="lead",
        ),
        migrations.AddField(
            model_name="department",
            name="lead",
            field=models.ManyToManyField(
                blank=True, related_name="lead_departments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
